/**
 * 
 */

var editor = {
	"description": "Welcome to Angry Webcomics! Zine. I have selected you the most angry comics of all webcomics.",
	"post": "More comics will be added soon. To start, I do recommend you to check out Wittgenstein Ant Colony to read about those small creatures with big adventures. Some more panels added this week. Enjoy reading!",
};

var comics = {
	"comicsList": [
       	{'folderUrl': '/Users/thuttula/development/xinkymics/xinkycomics/test/comic0/', 'dataFile': 'testComicData1.js',
	    	'icon': 'Icon.png', 
	    	'title': 'Seed',
	    	'description': 'Seed',
	    	'panelCount': 18,
	    	'creatorUrl': 'http://seedcomic.smackjeeves.com',
	    	'creatorNames' : 'Drobvirks',			
	    },
       	{'folderUrl': '/Users/thuttula/development/xinkymics/xinkycomics/test/comic1/', 'dataFile': 'testComicData1.js',
	    	'icon': 'Icon.png', 
	    	'title': 'Two Kinds',
	    	'description': 'Two Kinds',
	    	'panelCount': 23,
	    	'creatorUrl': 'http://twokinds.keenspot.com/',
	    	'creatorNames' : 'Tom Fischbach',			
	    },
		{'folderUrl': 'http://mobcomics.com/test/saintmakers1/wrt/', 'dataFile': 'testComicData1.js',
			'icon': 'Icon.png', 
			'title': 'Raging Saintmakers Square',
			'description': 'A story about a cannibal in a bustle, a trainee diplomat, and a very large fish.',
			'panelCount': 101,
			'creatorUrl': 'http://www.viistar.com',
			'creatorNames' : 'Renee Yoch',			
		},
		{'folderUrl': 'http://mobcomics.com/test/Pewfell_15_1/wrt/', 'dataFile': 'testComicData1.js',
			'icon': 'Icon.png', 
			'title': 'Pewfell',
			'description': 'Tina the Warrior princess is pregnant, and her slacker wizard of a husband Pewfell, after having accidentally blown up his study, must take a job with the city sewer patrol in order to pay the bills.',
			'panelCount': 152,
			'creatorUrl': 'http://www.stripamatic.com/~pewfell/pewfell/',
			'creatorNames' : 'Chuck Whelon',
		},
		{'folderUrl': 'http://mobcomics.com/test/rat/wrt/', 'dataFile': 'testComicData1.js',
			'icon': 'Icon.png', 
			'title': 'A Rat Named Bove',
			'description': 'The creature it stirs men to power and fame. But watch it carefully, for one ominous night the unwary will be fed to success and its relentless game!',
			'panelCount': 30,
			'creatorUrl': 'http://www.drawrick.com',
			'creatorNames' : 'Rick Lucey',
		},
		{'folderUrl': 'http://mobcomics.com/zines/comics/witt1/wrt/', 'dataFile': 'testComicData1.js',
			'icon': 'Icon.png', 
			'title': 'Wittgenstein Ant Colony',
			'description': 'The 30 Year War inspired black humored comic about a group of soldier ants on a long long march back to the hive.',
			'panelCount': 38,
			'creatorUrl': 'https://www.facebook.com/hermanstahlhandske',
			'creatorNames' : 'Herman Stahlhandske',
		},
		{'folderUrl': 'http://mobcomics.com/test/trojanCry0new/wrt/', 'dataFile': 'testComicData1.js',
			'icon': 'Icon.png', 
			'title': 'Trojan Cry0',
			'description': 'Earth is abandoned. Nature rules her kingdom once more. Humankind is scattered across the known worlds, isolated and persecuted. A concord is signed. Trojan is born.',
			'panelCount': 62,
			'creatorUrl': 'http://www.reapercomics.co.uk',
			'creatorNames' : 'Reaper Comics',
		},
	]
};
